import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'AgentKit Quickstart',
  description:
    'Generated by `create-onchain-agent`, a Next.js template for AgentKit',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen flex-col'>
        <main className='flex flex-grow items-center justify-center px-4'>
          {children}
        </main>
      </body>
    </html>
  );
}
